version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  rabbitmq:
    image: rabbitmq
    ports:
      - "5673:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  redis-data:
  rabbitmq_data:
